const GROUP_LABELS: Record<string, string> = {
  "10": "Capital",
  "11": "Reservas",
  "12": "Resultados pendientes",
  "13": "Subvenciones",
  "14": "Provisiones",
  "15": "Deudas a largo plazo",
  "16": "Deudas con partes vinculadas LP",
  "17": "Deudas por préstamos LP",
  "18": "Pasivos por fianzas LP",
  "19": "Situaciones transitorias",
  "20": "Inmovilizado intangible",
  "21": "Inmovilizado material",
  "22": "Inversiones inmobiliarias",
  "23": "Inmovilizado en curso",
  "24": "Inversiones financieras LP",
  "25": "Activos por impuesto diferido",
  "26": "Fianzas y depósitos constituidos LP",
  "27": "Activos por impuesto diferido",
  "28": "Amortización acumulada",
  "29": "Deterioro de valor",
  "30": "Comerciales",
  "31": "Materias primas",
  "32": "Otros aprovisionamientos",
  "33": "Productos en curso",
  "34": "Productos semiterminados",
  "35": "Productos terminados",
  "36": "Subproductos y residuos",
  "39": "Deterioro de valor de existencias",
  "40": "Proveedores",
  "41": "Acreedores varios",
  "43": "Clientes",
  "44": "Deudores varios",
  "46": "Personal",
  "47": "Administraciones públicas",
  "48": "Ajustes por periodificación",
  "49": "Deterioro de valor de créditos",
  "50": "Empréstitos y obligaciones",
  "51": "Deudas con partes vinculadas CP",
  "52": "Deudas a corto plazo",
  "53": "Inversiones financieras CP",
  "54": "Otras inversiones financieras CP",
  "55": "Otras cuentas no bancarias",
  "56": "Fianzas y depósitos recibidos CP",
  "57": "Tesorería",
  "58": "Inversiones financieras CP",
  "59": "Deterioro de valor de inversiones",
  "60": "Compras",
  "61": "Variación de existencias",
  "62": "Servicios exteriores",
  "63": "Tributos",
  "64": "Gastos de personal",
  "65": "Otros gastos de gestión",
  "66": "Gastos financieros",
  "67": "Pérdidas procedentes de activos",
  "68": "Dotaciones para amortizaciones",
  "69": "Pérdidas por deterioro",
  "70": "Ventas",
  "71": "Variación de existencias",
  "72": "Trabajos realizados para la empresa",
  "73": "Trabajos realizados para otros",
  "74": "Subvenciones",
  "75": "Otros ingresos de gestión",
  "76": "Ingresos financieros",
  "77": "Beneficios procedentes de activos",
  "78": "Ingresos excepcionales",
  "79": "Cargas excepcionales",
}

export function getAccountLabel(cuenta: string): string {
  const digits = cuenta.replace(/\D/g, "")
  if (!digits) return cuenta

  const prefix3 = digits.slice(0, 3)
  const prefix2 = digits.slice(0, 2)

  return GROUP_LABELS[prefix3] ?? GROUP_LABELS[prefix2] ?? `Cuenta ${digits}`
}
