import type { AccountingPlanType } from "@prisma/client"
import { formatAccountNameDisplay } from "@/lib/reports/format"
import {
  ACCOUNT_DETAIL_LEVEL_OPTIONS,
  BALANCE_FORMAT_OPTIONS,
  PROFIT_LOSS_FORMAT_OPTIONS,
  type GestoriaAccountDetailLevel,
  type GestoriaPresentationConfig,
} from "@/lib/contabilidad/gestoria-presentation-config"
import { ACCOUNTING_PLAN_OPTIONS } from "@/lib/contabilidad/gestoria-client-profile-types"

/** Nombres oficiales habituales del PGC 2008 (3 y 4 dígitos). */
export const PGC_CHART_NAMES: Record<string, string> = {
  "100": "Capital social",
  "101": "Fondo social",
  "102": "Capital",
  "103": "Socios por desembolsos no exigidos",
  "104": "Socios por aportaciones no dinerarias pendientes",
  "108": "Acciones o participaciones propias en situaciones especiales",
  "109": "Acciones o participaciones propias para reducción de capital",
  "110": "Prima de emisión o asunción",
  "112": "Reserva legal",
  "113": "Reservas voluntarias",
  "114": "Reservas especiales",
  "118": "Aportaciones de socios o propietarios",
  "119": "Diferencias por ajuste del capital a euros",
  "120": "Remanente",
  "121": "Resultados negativos de ejercicios anteriores",
  "129": "Resultado del ejercicio",
  "130": "Subvenciones oficiales de capital",
  "131": "Donaciones y legados de capital",
  "132": "Otras subvenciones, donaciones y legados",
  "137": "Ingresos fiscales a distribuir en varios ejercicios",
  "141": "Provisión para impuestos",
  "142": "Provisión para otras responsabilidades",
  "143": "Provisión por desmantelamiento, retiro o rehabilitación",
  "160": "Deudas a largo plazo con entidades de crédito vinculadas",
  "161": "Proveedores de inmovilizado a largo plazo, partes vinculadas",
  "162": "Acreedores por arrendamiento financiero a largo plazo, partes vinculadas",
  "163": "Otras deudas a largo plazo con partes vinculadas",
  "170": "Deudas a largo plazo con entidades de crédito",
  "171": "Deudas a largo plazo",
  "172": "Deudas a largo plazo transformables en subvenciones",
  "173": "Proveedores de inmovilizado a largo plazo",
  "174": "Acreedores por arrendamiento financiero a largo plazo",
  "175": "Efectos a pagar a largo plazo",
  "180": "Fianzas recibidas a largo plazo",
  "185": "Depósitos recibidos a largo plazo",
  "200": "Investigación",
  "201": "Desarrollo",
  "202": "Concesiones administrativas",
  "203": "Propiedad industrial",
  "205": "Derechos de traspaso",
  "206": "Aplicaciones informáticas",
  "210": "Terrenos y bienes naturales",
  "211": "Construcciones",
  "212": "Instalaciones técnicas",
  "213": "Maquinaria",
  "214": "Utillaje",
  "215": "Otras instalaciones",
  "216": "Mobiliario",
  "217": "Equipos para procesos de información",
  "218": "Elementos de transporte",
  "219": "Otro inmovilizado material",
  "220": "Inversiones en terrenos y bienes naturales",
  "221": "Inversiones en construcciones",
  "230": "Adaptación de terrenos y bienes naturales",
  "231": "Construcciones en curso",
  "232": "Instalaciones técnicas en montaje",
  "233": "Maquinaria en montaje",
  "237": "Equipos para procesos de información en montaje",
  "239": "Anticipos para inmovilizaciones materiales",
  "240": "Participaciones a largo plazo en partes vinculadas",
  "241": "Créditos a largo plazo a partes vinculadas",
  "249": "Desembolsos pendientes sobre participaciones a largo plazo",
  "250": "Inversiones financieras a largo plazo en instrumentos de patrimonio",
  "251": "Créditos a largo plazo",
  "252": "Créditos a largo plazo por enajenación de inmovilizado",
  "253": "Créditos a largo plazo al personal",
  "258": "Imposiciones a largo plazo",
  "260": "Fianzas constituidas a largo plazo",
  "265": "Depósitos constituidos a largo plazo",
  "280": "Amortización acumulada del inmovilizado intangible",
  "281": "Amortización acumulada del inmovilizado material",
  "282": "Amortización acumulada de las inversiones inmobiliarias",
  "290": "Deterioro de valor del inmovilizado intangible",
  "291": "Deterioro de valor del inmovilizado material",
  "292": "Deterioro de valor de las inversiones inmobiliarias",
  "293": "Deterioro de valor de participaciones a largo plazo",
  "294": "Deterioro de valor de créditos a largo plazo",
  "300": "Mercaderías",
  "310": "Materias primas",
  "320": "Otros aprovisionamientos",
  "326": "Embalajes",
  "327": "Envases",
  "330": "Productos en curso",
  "340": "Productos semiterminados",
  "350": "Productos terminados",
  "360": "Subproductos, residuos y materiales recuperados",
  "390": "Deterioro de valor de las existencias",
  "400": "Proveedores",
  "401": "Proveedores, efectos comerciales a pagar",
  "403": "Proveedores, empresas del grupo",
  "404": "Proveedores, empresas asociadas",
  "405": "Proveedores, otras partes vinculadas",
  "406": "Envases y embalajes a devolver a proveedores",
  "407": "Anticipos a proveedores",
  "410": "Acreedores por prestaciones de servicios",
  "411": "Acreedores, efectos comerciales a pagar",
  "419": "Acreedores por operaciones en común",
  "430": "Clientes",
  "431": "Clientes, efectos comerciales a cobrar",
  "432": "Clientes, empresas del grupo",
  "433": "Clientes, empresas asociadas",
  "434": "Clientes, otras partes vinculadas",
  "435": "Clientes de dudoso cobro",
  "436": "Clientes de dudoso cobro",
  "437": "Envases y embalajes a devolver por clientes",
  "438": "Anticipos de clientes",
  "440": "Deudores",
  "441": "Deudores, efectos comerciales a cobrar",
  "446": "Deudores de dudoso cobro",
  "449": "Deudores por operaciones en común",
  "460": "Anticipos de remuneraciones",
  "465": "Remuneraciones pendientes de pago",
  "466": "Remuneraciones mediante sistemas de aportación definida pendientes",
  "470": "Hacienda Pública, deudora por diversos conceptos",
  "4700": "Hacienda Pública, deudora por IVA",
  "471": "Organismos de la Seguridad Social, deudores",
  "472": "Hacienda Pública, IVA soportado",
  "473": "Hacienda Pública, retenciones y pagos a cuenta",
  "4730": "Hacienda Pública, retenciones y pagos a cuenta",
  "4731": "Hacienda Pública, retenciones IRPF",
  "4732": "Hacienda Pública, retenciones por arrendamientos",
  "474": "Activos por impuesto diferido",
  "475": "Hacienda Pública, acreedora por conceptos fiscales",
  "4750": "Hacienda Pública, acreedora por IVA",
  "4751": "Hacienda Pública, acreedora por retenciones practicadas",
  "4752": "Hacienda Pública, acreedora por impuesto sobre sociedades",
  "476": "Organismos de la Seguridad Social, acreedores",
  "477": "Hacienda Pública, IVA repercutido",
  "479": "Pasivos por diferencias temporarias imponibles",
  "480": "Gastos anticipados",
  "485": "Ingresos anticipados",
  "490": "Deterioro de valor de créditos por operaciones comerciales",
  "493": "Deterioro de valor de créditos por operaciones comerciales con partes vinculadas",
  "499": "Provisión para operaciones comerciales",
  "500": "Obligaciones y bonos a corto plazo",
  "510": "Deudas a corto plazo con entidades de crédito vinculadas",
  "511": "Proveedores de inmovilizado a corto plazo, partes vinculadas",
  "512": "Acreedores por arrendamiento financiero a corto plazo, partes vinculadas",
  "513": "Otras deudas a corto plazo con partes vinculadas",
  "520": "Deudas a corto plazo con entidades de crédito",
  "521": "Deudas a corto plazo",
  "522": "Deudas a corto plazo transformables en subvenciones",
  "523": "Proveedores de inmovilizado a corto plazo",
  "524": "Acreedores por arrendamiento financiero a corto plazo",
  "525": "Efectos a pagar a corto plazo",
  "526": "Dividendo activo a pagar",
  "527": "Intereses a corto plazo de deudas",
  "550": "Titular de la explotación",
  "551": "Cuenta corriente con socios y administradores",
  "552": "Cuenta corriente con otras personas y entidades vinculadas",
  "555": "Partidas pendientes de aplicación",
  "556": "Desembolsos exigidos sobre participaciones",
  "557": "Dividendo activo a cuenta",
  "558": "Socios por desembolsos exigidos",
  "560": "Fianzas recibidas a corto plazo",
  "561": "Depósitos recibidos a corto plazo",
  "565": "Fianzas constituidas a corto plazo",
  "566": "Depósitos constituidos a corto plazo",
  "570": "Caja, euros",
  "571": "Caja, moneda extranjera",
  "572": "Bancos e instituciones de crédito c/c vista, euros",
  "573": "Bancos e instituciones de crédito c/c vista, moneda extranjera",
  "574": "Bancos e instituciones de crédito, cuentas de ahorro",
  "575": "Bancos e instituciones de crédito, cuentas a plazo",
  "600": "Compras de mercaderías",
  "601": "Compras de materias primas",
  "602": "Compras de otros aprovisionamientos",
  "606": "Descuentos sobre compras por pronto pago",
  "607": "Trabajos realizados por otras empresas",
  "608": "Devoluciones de compras y operaciones similares",
  "609": "Rappels por compras",
  "610": "Variación de existencias de mercaderías",
  "611": "Variación de existencias de materias primas",
  "612": "Variación de existencias de otros aprovisionamientos",
  "620": "Gastos en investigación y desarrollo del ejercicio",
  "621": "Arrendamientos y cánones",
  "622": "Reparaciones y conservación",
  "623": "Servicios de profesionales independientes",
  "624": "Transportes",
  "625": "Primas de seguros",
  "626": "Servicios bancarios y similares",
  "627": "Publicidad, propaganda y relaciones públicas",
  "628": "Suministros",
  "629": "Otros servicios",
  "630": "Impuesto sobre beneficios",
  "631": "Otros tributos",
  "633": "Ajustes negativos en la imposición sobre beneficios",
  "634": "Ajustes negativos en la imposición indirecta",
  "636": "Devolución de impuestos",
  "638": "Ajustes positivos en la imposición sobre beneficios",
  "639": "Ajustes positivos en la imposición indirecta",
  "640": "Sueldos y salarios",
  "641": "Indemnizaciones",
  "642": "Seguridad Social a cargo de la empresa",
  "643": "Retribuciones a largo plazo mediante sistemas de aportación definida",
  "649": "Otros gastos sociales",
  "650": "Pérdidas de créditos comerciales incobrables",
  "651": "Resultados de operaciones en común",
  "659": "Otras pérdidas de gestión corriente",
  "660": "Gastos financieros por actualización de provisiones",
  "661": "Intereses de obligaciones y bonos",
  "662": "Intereses de deudas",
  "663": "Pérdidas por valoración de instrumentos financieros",
  "664": "Gastos por dividendos de acciones o participaciones",
  "665": "Intereses por descuento de efectos y operaciones de factoring",
  "666": "Pérdidas en participaciones y valores representativos de deuda",
  "667": "Pérdidas de créditos no comerciales",
  "668": "Diferencias negativas de cambio",
  "669": "Otros gastos financieros",
  "670": "Pérdidas procedentes del inmovilizado intangible",
  "671": "Pérdidas procedentes del inmovilizado material",
  "672": "Pérdidas procedentes de las inversiones inmobiliarias",
  "673": "Pérdidas procedentes de participaciones a largo plazo",
  "675": "Pérdidas por operaciones con obligaciones propias",
  "678": "Gastos excepcionales",
  "680": "Amortización del inmovilizado intangible",
  "681": "Amortización del inmovilizado material",
  "682": "Amortización de las inversiones inmobiliarias",
  "690": "Pérdidas por deterioro del inmovilizado intangible",
  "691": "Pérdidas por deterioro del inmovilizado material",
  "693": "Pérdidas por deterioro de existencias",
  "694": "Pérdidas por deterioro de créditos por operaciones comerciales",
  "696": "Pérdidas por deterioro de participaciones y valores",
  "700": "Ventas de mercaderías",
  "701": "Ventas de productos terminados",
  "702": "Ventas de productos semiterminados",
  "703": "Ventas de subproductos y residuos",
  "704": "Ventas de envases y embalajes",
  "705": "Prestaciones de servicios",
  "706": "Descuentos sobre ventas por pronto pago",
  "708": "Devoluciones de ventas y operaciones similares",
  "709": "Rappels sobre ventas",
  "710": "Variación de existencias de productos en curso",
  "711": "Variación de existencias de productos semiterminados",
  "712": "Variación de existencias de productos terminados",
  "713": "Variación de existencias de subproductos, residuos y materiales",
  "730": "Trabajos realizados para el inmovilizado intangible",
  "731": "Trabajos realizados para el inmovilizado material",
  "732": "Trabajos realizados en inversiones inmobiliarias",
  "733": "Trabajos realizados para el inmovilizado material en curso",
  "740": "Subvenciones, donaciones y legados a la explotación",
  "746": "Subvenciones, donaciones y legados de capital transferidos al resultado",
  "747": "Otras subvenciones, donaciones y legados transferidos al resultado",
  "751": "Resultados de operaciones en común",
  "752": "Ingresos por arrendamientos",
  "753": "Ingresos de propiedad industrial cedida en explotación",
  "754": "Ingresos por comisiones",
  "755": "Ingresos por servicios al personal",
  "759": "Ingresos por servicios diversos",
  "760": "Ingresos de participaciones en instrumentos de patrimonio",
  "761": "Ingresos de valores representativos de deuda",
  "762": "Ingresos de créditos",
  "763": "Beneficios por valoración de instrumentos financieros",
  "766": "Beneficios en participaciones y valores representativos de deuda",
  "768": "Diferencias positivas de cambio",
  "769": "Otros ingresos financieros",
  "770": "Beneficios procedentes del inmovilizado intangible",
  "771": "Beneficios procedentes del inmovilizado material",
  "772": "Beneficios procedentes de las inversiones inmobiliarias",
  "773": "Beneficios procedentes de participaciones a largo plazo",
  "775": "Beneficios por operaciones con obligaciones propias",
  "778": "Ingresos excepcionales",
  "790": "Reversión del deterioro del inmovilizado intangible",
  "791": "Reversión del deterioro del inmovilizado material",
  "793": "Reversión del deterioro de existencias",
  "794": "Reversión del deterioro de créditos por operaciones comerciales",
  "796": "Reversión del deterioro de participaciones y valores",
}

const PYME_CODES = [
  "100", "102", "103", "104", "108", "109", "110", "112", "113", "114", "118", "119",
  "120", "121", "129", "130", "131", "132", "137", "141", "142", "143",
  "170", "171", "172", "173", "174", "175", "180", "185",
  "200", "201", "202", "203", "205", "206",
  "210", "211", "212", "213", "214", "215", "216", "217", "218", "219",
  "230", "231", "232", "233", "237", "239",
  "250", "251", "252", "253", "258", "260", "265",
  "280", "281", "290", "291", "293", "294",
  "300", "310", "320", "326", "327", "330", "340", "350", "360", "390",
  "400", "401", "406", "407", "410", "411", "419",
  "430", "431", "435", "437", "438", "440", "441", "446", "449",
  "460", "465", "466", "470", "471", "472", "473", "474", "475", "476", "477", "479",
  "480", "485", "490", "499",
  "520", "521", "522", "523", "524", "525", "526", "527",
  "550", "551", "555", "556", "557", "558", "560", "561", "565", "566",
  "570", "571", "572", "573", "574", "575",
  "600", "601", "602", "606", "607", "608", "609", "610", "611", "612",
  "620", "621", "622", "623", "624", "625", "626", "627", "628", "629",
  "630", "631", "633", "634", "636", "638", "639",
  "640", "641", "642", "649", "650", "651", "659",
  "662", "665", "666", "668", "669",
  "670", "671", "678", "680", "681", "691", "693", "694",
  "700", "701", "702", "703", "704", "705", "706", "708", "709",
  "710", "711", "712", "713",
  "730", "731", "733", "740", "746", "747",
  "751", "752", "753", "754", "755", "759",
  "760", "761", "762", "768", "769",
  "770", "771", "778", "791", "793", "794",
] as const

const GENERAL_EXTRA_CODES = [
  "101", "160", "161", "162", "163",
  "220", "221", "240", "241", "249",
  "282", "292",
  "403", "404", "405", "432", "433", "434", "493",
  "500", "510", "511", "512", "513",
  "552", "643", "660", "661", "663", "664", "667",
  "672", "673", "675", "682", "690", "696",
  "732", "763", "766", "772", "773", "775", "790", "796",
] as const

const MICRO_EXCLUDED = new Set([
  "103", "104", "108", "109", "118", "119", "137", "143",
  "172", "174", "175",
  "200", "201", "230", "231", "232", "233", "237", "239",
  "250", "252", "253", "258", "293", "294",
  "326", "327", "330", "340", "350", "360",
  "401", "406", "411", "419", "431", "435", "437", "441", "446", "449", "466",
  "474", "479", "490", "499",
  "522", "524", "525", "526", "527", "556", "557", "558",
  "571", "573", "574", "575",
  "606", "609", "611", "612",
  "633", "634", "638", "639", "643", "651",
  "665", "666",
  "670", "691", "693",
  "701", "702", "703", "704", "706", "709", "710", "711", "712", "713",
  "730", "731", "733", "746", "747", "751", "753",
  "760", "761", "768",
  "770", "791", "793",
])

const NIVEL_4_CHILDREN: Record<string, string[]> = {
  "470": ["4700"],
  "473": ["4730", "4731", "4732"],
  "475": ["4750", "4751", "4752"],
}

export interface CompanyChartPlanInfo {
  accountingPlanType: AccountingPlanType
  accountingPlanLabel: string
  balanceFormat: GestoriaPresentationConfig["balanceFormat"]
  balanceCode: string
  balanceLabel: string
  profitLossFormat: GestoriaPresentationConfig["profitLossFormat"]
  profitLossCode: string
  profitLossLabel: string
  detailLevel: GestoriaAccountDetailLevel
  detailLevelLabel: string
}

export function getChartAccountName(code: string): string {
  return formatAccountNameDisplay(PGC_CHART_NAMES[code] ?? `Cuenta ${code}`)
}

export function getPlanAccountCodes(planType: AccountingPlanType): string[] {
  if (planType === "PGC_GENERAL") {
    return uniqueSorted([...PYME_CODES, ...GENERAL_EXTRA_CODES])
  }
  if (planType === "PGC_MICRO") {
    return PYME_CODES.filter((code) => !MICRO_EXCLUDED.has(code))
  }
  return [...PYME_CODES]
}

export function expandPlanCodesForDetail(
  planCodes: string[],
  detailLevel: GestoriaAccountDetailLevel,
): string[] {
  if (detailLevel !== "NIVEL_4") return planCodes
  const expanded: string[] = []
  for (const code of planCodes) {
    const children = NIVEL_4_CHILDREN[code]
    if (children) expanded.push(...children)
    else expanded.push(code)
  }
  return uniqueSorted(expanded)
}

export function describeCompanyChartPlan(
  planType: AccountingPlanType,
  presentation: GestoriaPresentationConfig,
): CompanyChartPlanInfo {
  const balance =
    BALANCE_FORMAT_OPTIONS.find((item) => item.id === presentation.balanceFormat) ??
    BALANCE_FORMAT_OPTIONS[0]
  const pyg =
    PROFIT_LOSS_FORMAT_OPTIONS.find((item) => item.id === presentation.profitLossFormat) ??
    PROFIT_LOSS_FORMAT_OPTIONS[0]
  const detail =
    ACCOUNT_DETAIL_LEVEL_OPTIONS.find(
      (item) => item.id === presentation.annualAccounts.accountDetailLevel,
    ) ?? ACCOUNT_DETAIL_LEVEL_OPTIONS[0]

  return {
    accountingPlanType: planType,
    accountingPlanLabel:
      ACCOUNTING_PLAN_OPTIONS.find((item) => item.id === planType)?.label ?? planType,
    balanceFormat: presentation.balanceFormat,
    balanceCode: balance.code,
    balanceLabel: balance.label,
    profitLossFormat: presentation.profitLossFormat,
    profitLossCode: pyg.code,
    profitLossLabel: pyg.label,
    detailLevel: presentation.annualAccounts.accountDetailLevel,
    detailLevelLabel: detail.label,
  }
}

function uniqueSorted(codes: string[]): string[] {
  return [...new Set(codes)].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
}
